POST localhost:8080/trips/generate
Content-Type: application/json
X-Request-ID: test-request-id-11

{
  "cityId": "new-york"
}

###

GET http://localhost:8080/request
user: pkslow

###

GET http://localhost:8083/cities/new-york?trace=true
user: pkslow
X-Request-ID: test-request-id-10

###

