package net.serebryansky.common

import java.lang.RuntimeException
import java.lang.Runnable
import org.springframework.web.server.WebFilter
import org.springframework.web.server.ServerWebExchange
import org.springframework.web.server.WebFilterChain
import java.lang.Void
import net.serebryansky.common.util.LoggingUtil
import net.serebryansky.common.filter.RequestIdFilter
import org.springframework.web.reactive.function.client.WebClient
import net.serebryansky.common.service.CityService
import net.serebryansky.city.model.City
import net.serebryansky.common.service.impl.CityServiceImpl
import reactor.util.context.ContextView
import net.serebryansky.common.service.PlaceService
import reactor.core.publisher.Flux
import net.serebryansky.place.model.Place
import net.serebryansky.common.service.impl.PlaceServiceImpl
import net.serebryansky.common.service.RoutingService
import net.serebryansky.routing.model.DurationMatrixResponse
import net.serebryansky.common.service.impl.RoutingServiceImpl
import net.serebryansky.routing.model.RouteSearchRequest
import net.serebryansky.common.service.TripBuilderService
import net.serebryansky.nology.model.Trip
import net.serebryansky.builder.model.TripBuilderResponse
import net.serebryansky.common.service.impl.TripBuilderServiceImpl
